version: 2
updates:
  - package-ecosystem: "docker"
    directory: "24.04"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "docker"
      include: "scope"
    open-pull-requests-limit: 5

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
