name: Build & Push Docker images

on:
  workflow_dispatch:              # manual trigger

permissions:                      # allow GITHUB_TOKEN to push to GHCR
  contents: read
  packages: write

env:
  IMAGE_NAME: ghcr.io/${{ github.repository }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: ["24.04"]   # <-- add more folders here as needed

    steps:
      # 1 – Check out code -----------------------------------------------
      - uses: actions/checkout@v4

      # 2 – (Optional) multi-arch emulation ------------------------------
      - uses: docker/setup-qemu-action@v3

      # 3 – Buildx builder ----------------------------------------------
      - uses: docker/setup-buildx-action@v3

      # 4 – Log in to GitHub Container Registry -------------------------
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # 5 – Generate tags/labels ----------------------------------------
      - id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.IMAGE_NAME }}
          tags: |
            type=raw,value=${{ matrix.version }}            # e.g. :22.04
            type=sha,format=short,prefix=${{ matrix.version }}-  # e.g. :22.04-abc1234
            type=ref,event=branch                           # :main, :feature-x …
          labels: |
            org.opencontainers.image.version=${{ matrix.version }}
            org.opencontainers.image.source=${{ github.repositoryUrl }}

      # 6 – Build & push -------------------------------------------------
      - uses: docker/build-push-action@v6
        with:
          context: ${{ matrix.version }}        # build the matching folder
          platforms: linux/amd64,linux/arm64    # comment out if not needed
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
